name: Heart Disease Preprocessing Pipeline

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  preprocessing:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install -r preprocessing/requirements.txt

      - name: Run Preprocessing Script
        run: |
          python preprocessing/automate_Zulfiana-Majid.py
